pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
